// 100 of the most popular music artists of all time, including Michael Jackson.
// Each entry has a display name and a broad genre tag used on the result card.
const ARTISTS = [
  { name: "Michael Jackson", genre: "Pop / R&B" },
  { name: "The Beatles", genre: "Rock / Pop" },
  { name: "Elvis Presley", genre: "Rock 'n' Roll" },
  { name: "Madonna", genre: "Pop" },
  { name: "Whitney Houston", genre: "R&B / Pop" },
  { name: "Prince", genre: "Funk / Pop / Rock" },
  { name: "Stevie Wonder", genre: "Soul / R&B" },
  { name: "Beyoncé", genre: "R&B / Pop" },
  { name: "Taylor Swift", genre: "Pop / Country" },
  { name: "Rihanna", genre: "Pop / R&B" },
  { name: "Adele", genre: "Pop / Soul" },
  { name: "Ed Sheeran", genre: "Pop / Folk" },
  { name: "Bruno Mars", genre: "Pop / Funk" },
  { name: "Drake", genre: "Hip-Hop / R&B" },
  { name: "Kanye West", genre: "Hip-Hop" },
  { name: "Jay-Z", genre: "Hip-Hop" },
  { name: "Eminem", genre: "Hip-Hop" },
  { name: "Kendrick Lamar", genre: "Hip-Hop" },
  { name: "Nicki Minaj", genre: "Hip-Hop" },
  { name: "Cardi B", genre: "Hip-Hop" },
  { name: "Ariana Grande", genre: "Pop / R&B" },
  { name: "Justin Bieber", genre: "Pop" },
  { name: "Justin Timberlake", genre: "Pop / R&B" },
  { name: "Lady Gaga", genre: "Pop" },
  { name: "Katy Perry", genre: "Pop" },
  { name: "Britney Spears", genre: "Pop" },
  { name: "Christina Aguilera", genre: "Pop" },
  { name: "Mariah Carey", genre: "Pop / R&B" },
  { name: "Celine Dion", genre: "Pop" },
  { name: "Elton John", genre: "Pop / Rock" },
  { name: "Queen", genre: "Rock" },
  { name: "David Bowie", genre: "Rock / Pop" },
  { name: "Bob Marley", genre: "Reggae" },
  { name: "Bob Dylan", genre: "Folk / Rock" },
  { name: "Bruce Springsteen", genre: "Rock" },
  { name: "The Rolling Stones", genre: "Rock" },
  { name: "Led Zeppelin", genre: "Rock" },
  { name: "Pink Floyd", genre: "Rock" },
  { name: "AC/DC", genre: "Rock" },
  { name: "Guns N' Roses", genre: "Rock" },
  { name: "Nirvana", genre: "Rock / Grunge" },
  { name: "Metallica", genre: "Metal" },
  { name: "Aerosmith", genre: "Rock" },
  { name: "U2", genre: "Rock" },
  { name: "Coldplay", genre: "Rock / Pop" },
  { name: "Radiohead", genre: "Rock" },
  { name: "Fleetwood Mac", genre: "Rock" },
  { name: "The Who", genre: "Rock" },
  { name: "Eagles", genre: "Rock" },
  { name: "Journey", genre: "Rock" },
  { name: "Van Halen", genre: "Rock" },
  { name: "Ozzy Osbourne", genre: "Metal / Rock" },
  { name: "Johnny Cash", genre: "Country" },
  { name: "Dolly Parton", genre: "Country" },
  { name: "Willie Nelson", genre: "Country" },
  { name: "Garth Brooks", genre: "Country" },
  { name: "Shania Twain", genre: "Country / Pop" },
  { name: "Carrie Underwood", genre: "Country" },
  { name: "Luke Combs", genre: "Country" },
  { name: "Chris Stapleton", genre: "Country" },
  { name: "Tupac Shakur", genre: "Hip-Hop" },
  { name: "The Notorious B.I.G.", genre: "Hip-Hop" },
  { name: "Snoop Dogg", genre: "Hip-Hop" },
  { name: "Dr. Dre", genre: "Hip-Hop" },
  { name: "50 Cent", genre: "Hip-Hop" },
  { name: "Nas", genre: "Hip-Hop" },
  { name: "Lil Wayne", genre: "Hip-Hop" },
  { name: "Missy Elliott", genre: "Hip-Hop" },
  { name: "OutKast", genre: "Hip-Hop" },
  { name: "Usher", genre: "R&B" },
  { name: "Chris Brown", genre: "R&B" },
  { name: "Alicia Keys", genre: "R&B" },
  { name: "John Legend", genre: "R&B" },
  { name: "The Weeknd", genre: "R&B / Pop" },
  { name: "Frank Ocean", genre: "R&B" },
  { name: "SZA", genre: "R&B" },
  { name: "Billie Eilish", genre: "Pop / Alternative" },
  { name: "Post Malone", genre: "Hip-Hop / Pop" },
  { name: "Travis Scott", genre: "Hip-Hop" },
  { name: "Harry Styles", genre: "Pop / Rock" },
  { name: "Shawn Mendes", genre: "Pop" },
  { name: "Selena Gomez", genre: "Pop" },
  { name: "Demi Lovato", genre: "Pop" },
  { name: "Miley Cyrus", genre: "Pop" },
  { name: "Lana Del Rey", genre: "Pop / Alternative" },
  { name: "Dua Lipa", genre: "Pop" },
  { name: "Sia", genre: "Pop" },
  { name: "Sam Smith", genre: "Pop / Soul" },
  { name: "Amy Winehouse", genre: "Soul / Jazz" },
  { name: "George Michael", genre: "Pop" },
  { name: "Wham!", genre: "Pop" },
  { name: "ABBA", genre: "Pop" },
  { name: "Bee Gees", genre: "Pop / Disco" },
  { name: "Diana Ross", genre: "Motown / Pop" },
  { name: "The Jackson 5", genre: "Motown / Pop" },
  { name: "Ray Charles", genre: "Soul / R&B" },
  { name: "Aretha Franklin", genre: "Soul" },
  { name: "James Brown", genre: "Funk / Soul" },
  { name: "Marvin Gaye", genre: "Motown / Soul" },
  { name: "Louis Armstrong", genre: "Jazz" },
];

if (typeof module !== "undefined" && module.exports) {
  module.exports = ARTISTS;
}
